# Generated by Django 4.0.1 on 2022-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
