# Generated by Django 4.0.1 on 2022-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_ticket_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
